spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Xiaohei_CCsqr/tensquare_duiduo.git
  rabbitmq:
    host: 192.168.137.129
server:
  port: 12000
management:  #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh